//TODO none of these are fixed, used for placeholder purposed only
export const dummyPerformanceList = [
  {
    no: 1,
    branchId: "JKT",
    shipmentType: "Dedicated",
    driverId: 2342333,
    driverName: "xxx",
    driverVKVD: "xxx",
    totalShipment: 10,
    totalWorkdays: 12,
    totalClockIn: 8,
    totalOnTimePickup: 7,
    totalOnTimeDelivery: 8,
    totalOnTimePodReturn: 12,
    totalClaimShipment: 3,
    totalHarshShipment: 12,
    ciCompliance: "50%",
    onTimePickup: "10%",
    onTimeDelivery: "80%",
    podHandling: "15%",
    claim: "20%",
    harshShipment: "17%",
    accident: 2,
    average: "20%",
    score: "A",
  },
  {
    no: 2,
    branchId: "JKT",
    shipmentType: "Dedicated",
    driverId: 2342333,
    driverName: "xxx",
    driverVKVD: "xxx",
    totalShipment: 10,
    totalWorkdays: 12,
    totalClockIn: 8,
    totalOnTimePickup: 7,
    totalOnTimeDelivery: 8,
    totalOnTimePodReturn: 12,
    totalClaimShipment: 3,
    totalHarshShipment: 12,
    ciCompliance: "50%",
    onTimePickup: "10%",
    onTimeDelivery: "80%",
    podHandling: "15%",
    claim: "20%",
    harshShipment: "17%",
    accident: 2,
    average: "20%",
    score: "A",
  },
  {
    no: 3,
    branchId: "JKT",
    shipmentType: "Dedicated",
    driverId: 2342333,
    driverName: "xxx",
    driverVKVD: "xxx",
    totalShipment: 10,
    totalWorkdays: 12,
    totalClockIn: 8,
    totalOnTimePickup: 7,
    totalOnTimeDelivery: 8,
    totalOnTimePodReturn: 12,
    totalClaimShipment: 3,
    totalHarshShipment: 12,
    ciCompliance: "50%",
    onTimePickup: "10%",
    onTimeDelivery: "80%",
    podHandling: "15%",
    claim: "20%",
    harshShipment: "17%",
    accident: 2,
    average: "20%",
    score: "A",
  },
  {
    no: 4,
    branchId: "JKT",
    shipmentType: "Dedicated",
    driverId: 2342333,
    driverName: "xxx",
    driverVKVD: "xxx",
    totalShipment: 10,
    totalWorkdays: 12,
    totalClockIn: 8,
    totalOnTimePickup: 7,
    totalOnTimeDelivery: 8,
    totalOnTimePodReturn: 12,
    totalClaimShipment: 3,
    totalHarshShipment: 12,
    ciCompliance: "50%",
    onTimePickup: "10%",
    onTimeDelivery: "80%",
    podHandling: "15%",
    claim: "20%",
    harshShipment: "17%",
    accident: 2,
    average: "20%",
    score: "B",
  },
  {
    no: 5,
    branchId: "JKT",
    shipmentType: "Dedicated",
    driverId: 2342333,
    driverName: "xxx",
    driverVKVD: "xxx",
    totalShipment: 10,
    totalWorkdays: 12,
    totalClockIn: 8,
    totalOnTimePickup: 7,
    totalOnTimeDelivery: 8,
    totalOnTimePodReturn: 12,
    totalClaimShipment: 3,
    totalHarshShipment: 12,
    ciCompliance: "50%",
    onTimePickup: "10%",
    onTimeDelivery: "80%",
    podHandling: "15%",
    claim: "20%",
    harshShipment: "17%",
    accident: 2,
    average: "20%",
    score: "A",
  },
  {
    no: 6,
    branchId: "JKT",
    shipmentType: "Dedicated",
    driverId: 2342333,
    driverName: "xxx",
    driverVKVD: "xxx",
    totalShipment: 10,
    totalWorkdays: 12,
    totalClockIn: 8,
    totalOnTimePickup: 7,
    totalOnTimeDelivery: 8,
    totalOnTimePodReturn: 12,
    totalClaimShipment: 3,
    totalHarshShipment: 12,
    ciCompliance: "50%",
    onTimePickup: "10%",
    onTimeDelivery: "80%",
    podHandling: "15%",
    claim: "20%",
    harshShipment: "17%",
    accident: 2,
    average: "20%",
    score: "B",
  },
  {
    no: 7,
    branchId: "JKT",
    shipmentType: "Dedicated",
    driverId: 2342333,
    driverName: "xxx",
    driverVKVD: "xxx",
    totalShipment: 10,
    totalWorkdays: 12,
    totalClockIn: 8,
    totalOnTimePickup: 7,
    totalOnTimeDelivery: 8,
    totalOnTimePodReturn: 12,
    totalClaimShipment: 3,
    totalHarshShipment: 12,
    ciCompliance: "50%",
    onTimePickup: "10%",
    onTimeDelivery: "80%",
    podHandling: "15%",
    claim: "20%",
    harshShipment: "17%",
    accident: 2,
    average: "20%",
    score: "B",
  },
  {
    no: 8,
    branchId: "JKT",
    shipmentType: "Dedicated",
    driverId: 2342333,
    driverName: "xxx",
    driverVKVD: "xxx",
    totalShipment: 10,
    totalWorkdays: 12,
    totalClockIn: 8,
    totalOnTimePickup: 7,
    totalOnTimeDelivery: 8,
    totalOnTimePodReturn: 12,
    totalClaimShipment: 3,
    totalHarshShipment: 12,
    ciCompliance: "50%",
    onTimePickup: "10%",
    onTimeDelivery: "80%",
    podHandling: "15%",
    claim: "20%",
    harshShipment: "17%",
    accident: 2,
    average: "20%",
    score: "C",
  },
  {
    no: 9,
    branchId: "JKT",
    shipmentType: "Dedicated",
    driverId: 2342333,
    driverName: "xxx",
    driverVKVD: "xxx",
    totalShipment: 10,
    totalWorkdays: 12,
    totalClockIn: 8,
    totalOnTimePickup: 7,
    totalOnTimeDelivery: 8,
    totalOnTimePodReturn: 12,
    totalClaimShipment: 3,
    totalHarshShipment: 12,
    ciCompliance: "50%",
    onTimePickup: "10%",
    onTimeDelivery: "80%",
    podHandling: "15%",
    claim: "20%",
    harshShipment: "17%",
    accident: 2,
    average: "20%",
    score: "C",
  },
  {
    no: 10,
    branchId: "JKT",
    shipmentType: "Dedicated",
    driverId: 2342333,
    driverName: "xxx",
    driverVKVD: "xxx",
    totalShipment: 10,
    totalWorkdays: 12,
    totalClockIn: 8,
    totalOnTimePickup: 7,
    totalOnTimeDelivery: 8,
    totalOnTimePodReturn: 12,
    totalClaimShipment: 3,
    totalHarshShipment: 12,
    ciCompliance: "50%",
    onTimePickup: "10%",
    onTimeDelivery: "80%",
    podHandling: "15%",
    claim: "20%",
    harshShipment: "17%",
    accident: 2,
    average: "20%",
    score: "B",
  },
];

export const dummyDriverList = [
  {
    label: "Driver Name",
    value: "driver_name",
    options: [],
  },
  {
    label: "Grade",
    value: "grade",
    options: [
      { label: "A", value: "a" },
      { label: "B", value: "b" },
      { label: "C", value: "c" },
    ],
  },
];

export const dummyBranchList = [
  {
    label: "Banjarmasin",
    value: "a",
  },
  {
    label: "Balikpapan",
    value: "b",
  },
  {
    label: "Jakarta",
    value: "c",
  },
  {
    label: "Makassar",
    value: "d",
  },
  {
    label: "Semarang",
    value: "e",
  },
  {
    label: "Surabaya",
    value: "f",
  },
];

export const dummyEmployeeList = [
  {
    label: "PKWT",
    value: "a",
  },
  {
    label: "MITRA",
    value: "b",
  },
];

export const dummyShipmentList = [
  {
    label: "Ritase",
    value: "a",
  },
  {
    label: "Dedicated",
    value: "b",
  },
];

export const dummyQuestionaire = [
  {
    no: 1,
    question: "Apakah driver sudah cukup tidur minimal 6 jam?",
    answer: "yes",
  },
  {
    no: 2,
    question: "Apakah driver mengkonsumsi alkohol dan narkoba?",
    answer: "no",
  },
  {
    no: 3,
    question: "Apakah kondisi mata driver merah?",
    answer: "no",
  },
  {
    no: 4,
    question: "Apakah kondisi mata driver berair atau kering?",
    answer: "no",
  },
  {
    no: 5,
    question: "Apakah mata sensitif terhadap cahaya?",
    answer: "no",
  },
  {
    no: 6,
    question: "Apakah pandangan kabur atau berbayang?",
    answer: "no",
  },
];
