export const STATUS = {
  processing: [
    "FREE ARAH BALIK",
    "PAIRED",
    "PLANNED",
    "UPLOADING",
    "WAITING FOR APPROVAL",
    "ADDITIONAL EXPENSE REQUESTED",
    "LOADING",
    "SHIPMENT ON DUTY",
  ],
  success: [
    "ACTIVE",
    "APPROVED",
    "ASSIGNED",
    "COMPLETED",
    "IN PROGRESS",
    "LOW",
    "SUCCESS",
    "USP",
    "CONFIRMED",
    "APPROVED",
    "ADDITIONAL EXPENSE APPROVED",
    "UNLOADING",
  ],
  error: [
    "CANCELLED",
    "DELAYED",
    "EXPIRED",
    "FAILED",
    "HIGH",
    "LATE",
    "NO OBD",
    "REJECTED",
    "REPAIRED",
    "UTSP",
    "REJECTED",
  ],
  warning: [
    "ARAH BALIK",
    "ATTENTION",
    "CHANGED",
    "DELAY",
    "DRAFT",
    "FINISHING UP",
    "INCOMPLETE",
    "INCOMPLETED",
    "MEDIUM",
    "NEED TO CONFIRM",
    "REQUESTED",
    "SLEEPING",
    "UNASSIGNED",
    "ADDITIONAL EXPENSE ON APPROVAL",
    "ON JOURNEY",
  ],
};
