import { HttpStatusCodesProps } from "./types";

export const HTTP_STATUS_CODES: HttpStatusCodesProps[] = [
  { code: 100, message: "", text: "Continue", type: "success" },
  { code: 101, message: "", text: "Switching Protocols", type: "success" },
  { code: 102, message: "", text: "Processing", type: "success" },
  { code: 103, message: "", text: "Early Hints", type: "success" },
  { code: 200, message: "", text: "OK", type: "success" },
  { code: 201, message: "", text: "Created", type: "success" },
  { code: 202, message: "", text: "Accepted", type: "success" },
  {
    code: 203,
    message: "",
    text: "Non-Authoritative Information",
    type: "success",
  },
  { code: 204, message: "", text: "No Content", type: "success" },
  { code: 205, message: "", text: "Reset Content", type: "success" },
  { code: 206, message: "", text: "Partial Content", type: "success" },
  { code: 207, message: "", text: "Multi-Status", type: "success" },
  { code: 208, message: "", text: "Already Reported", type: "success" },
  { code: 226, message: "", text: "IM Used", type: "success" },
  { code: 300, message: "", text: "Multiple Choices", type: "success" },
  { code: 301, message: "", text: "Moved Permanently", type: "success" },
  { code: 302, message: "", text: "Found", type: "success" },
  { code: 303, message: "", text: "See Other", type: "success" },
  { code: 304, message: "", text: "Not Modified", type: "success" },
  { code: 305, message: "", text: "Use Proxy", type: "success" },
  { code: 307, message: "", text: "Temporary Redirect", type: "success" },
  { code: 308, message: "", text: "Permanent Redirect", type: "success" },
  { code: 400, message: "", text: "Bad Request", type: "failed" },
  { code: 401, message: "", text: "Unauthorized", type: "failed" },
  { code: 402, message: "", text: "Payment Required", type: "failed" },
  { code: 403, message: "", text: "Forbidden", type: "failed" },
  { code: 404, message: "Not Found", text: "Not Found", type: "failed" },
  { code: 405, message: "", text: "Method Not Allowed", type: "failed" },
  { code: 406, message: "", text: "Not Acceptable", type: "failed" },
  {
    code: 407,
    message: "",
    text: "Proxy Authentication Required",
    type: "failed",
  },
  { code: 408, message: "", text: "Request Timeout", type: "failed" },
  { code: 409, message: "", text: "Conflict", type: "failed" },
  { code: 410, message: "", text: "Gone", type: "failed" },
  { code: 411, message: "", text: "Length Required", type: "failed" },
  { code: 412, message: "", text: "Precondition Failed", type: "failed" },
  { code: 413, message: "", text: "Payload Too Large", type: "failed" },
  { code: 414, message: "", text: "URI Too Long", type: "failed" },
  { code: 415, message: "", text: "Unsupported Media Type", type: "failed" },
  { code: 416, message: "", text: "Range Not Satisfiable", type: "failed" },
  { code: 417, message: "", text: "Expectation Failed", type: "failed" },
  { code: 418, message: "", text: "I'm a teapot", type: "failed" },
  { code: 421, message: "", text: "Misdirected Request", type: "failed" },
  { code: 422, message: "", text: "Unprocessable Entity", type: "failed" },
  { code: 423, message: "", text: "Locked", type: "failed" },
  { code: 424, message: "", text: "Failed Dependency", type: "failed" },
  { code: 426, message: "", text: "Upgrade Required", type: "failed" },
  { code: 428, message: "", text: "Precondition Required", type: "failed" },
  { code: 429, message: "", text: "Too Many Requests", type: "failed" },
  {
    code: 431,
    message: "",
    text: "Request Header Fields Too Large",
    type: "failed",
  },
  {
    code: 451,
    message: "",
    text: "Unavailable For Legal Reasons",
    type: "failed",
  },
  {
    code: 500,
    message: "Server is under maintenance!",
    text: "Internal Server Error",
    type: "failed",
  },
  {
    code: 501,
    message: "Server is under maintenance!",
    text: "Not Implemented",
    type: "failed",
  },
  {
    code: 502,
    message: "Server is under maintenance!",
    text: "Bad Gateway",
    type: "failed",
  },
  {
    code: 503,
    message: "Server is under maintenance!",
    text: "Service Unavailable",
    type: "failed",
  },
  {
    code: 504,
    message: "Server is under maintenance!",
    text: "Gateway Timeout",
    type: "failed",
  },
  {
    code: 505,
    message: "Server is under maintenance!",
    text: "HTTP Version Not Supported",
    type: "failed",
  },
  {
    code: 506,
    message: "Server is under maintenance!",
    text: "Variant Also Negotiates",
    type: "failed",
  },
  {
    code: 507,
    message: "Server is under maintenance!",
    text: "Insufficient Storage",
    type: "failed",
  },
  {
    code: 508,
    message: "Server is under maintenance!",
    text: "Loop Detected",
    type: "failed",
  },
  {
    code: 510,
    message: "Server is under maintenance!",
    text: "Not Extended",
    type: "failed",
  },
  {
    code: 511,
    message: "Server is under maintenance!",
    text: "Network Authentication Required",
    type: "failed",
  },
];
