//TODO none of these are fixed, used for placeholder purposed only
export const dummyFatigueList = [
  {
    no: 1,
    branchId: "JKT",
    shipmentType: "Dedicated",
    driverId: 2342333,
    driverName: "xxx",
    lastShipment: "Jakarta-Surabaya",
    numberOfTrip: 4,
    hoursDriven: 34,
    healthResult: "Self Pre-trip",
    operationResult: "pending",
    fatigueLevel: "low",
    recommendation: "Boleh Lanjut",
    updatedFrom: "Driver",
    updatedBy: "-",
    updatedDate: "-",
    id: 1,
  },
  {
    no: 2,
    branchId: "SBY",
    shipmentType: "Ritase",
    driverId: 2311111,
    driverName: "xxx",
    lastShipment: "Surabaya-Balikpapan",
    numberOfTrip: 5,
    hoursDriven: 40,
    healthResult: "Fit",
    operationResult: "pending",
    fatigueLevel: "low",
    recommendation: "Boleh Lanjut",
    updatedFrom: "Nakes",
    updatedBy: "-",
    updatedDate: "-",
    id: 2,
  },
  {
    no: 3,
    branchId: "SBY",
    shipmentType: "Ritase",
    driverId: 2311111,
    driverName: "xxx",
    lastShipment: "Surabaya-Balikpapan",
    numberOfTrip: 5,
    hoursDriven: 40,
    healthResult: "Fit",
    operationResult: "pending",
    fatigueLevel: "low",
    recommendation: "Boleh Lanjut",
    updatedFrom: "Nakes",
    updatedBy: "-",
    updatedDate: "-",
    id: 3,
  },
  {
    no: 4,
    branchId: "SBY",
    shipmentType: "Ritase",
    driverId: 2311111,
    driverName: "xxx",
    lastShipment: "Surabaya-Balikpapan",
    numberOfTrip: 5,
    hoursDriven: 40,
    healthResult: "Fit",
    operationResult: "pending",
    fatigueLevel: "high",
    recommendation: "Boleh Lanjut",
    updatedFrom: "Driver",
    updatedBy: "-",
    updatedDate: "-",
    id: 4,
  },
  {
    no: 5,
    branchId: "SBY",
    shipmentType: "Ritase",
    driverId: 2311111,
    driverName: "xxx",
    lastShipment: "Surabaya-Balikpapan",
    numberOfTrip: 5,
    hoursDriven: 40,
    healthResult: "Fit",
    operationResult: "pending",
    fatigueLevel: "low",
    recommendation: "Boleh Lanjut",
    updatedFrom: "Driver",
    updatedBy: "-",
    updatedDate: "-",
    id: 5,
  },
  {
    no: 6,
    branchId: "SBY",
    shipmentType: "Ritase",
    driverId: 2311111,
    driverName: "xxx",
    lastShipment: "Surabaya-Balikpapan",
    numberOfTrip: 5,
    hoursDriven: 40,
    healthResult: "Fit",
    operationResult: "pending",
    fatigueLevel: "high",
    recommendation: "Boleh Lanjut",
    updatedFrom: "Nakes",
    updatedBy: "-",
    updatedDate: "-",
    id: 6,
  },
  {
    no: 7,
    branchId: "SBY",
    shipmentType: "Ritase",
    driverId: 2311111,
    driverName: "xxx",
    lastShipment: "Surabaya-Balikpapan",
    numberOfTrip: 5,
    hoursDriven: 40,
    healthResult: "Fit",
    operationResult: "pending",
    fatigueLevel: "medium",
    recommendation: "Boleh Lanjut",
    updatedFrom: "Driver",
    updatedBy: "-",
    updatedDate: "-",
    id: 7,
  },
  {
    no: 8,
    branchId: "SBY",
    shipmentType: "Ritase",
    driverId: 2311111,
    driverName: "xxx",
    lastShipment: "Surabaya-Balikpapan",
    numberOfTrip: 5,
    hoursDriven: 40,
    healthResult: "Fit",
    operationResult: "pending",
    fatigueLevel: "low",
    recommendation: "Boleh Lanjut",
    updatedFrom: "Driver",
    updatedBy: "-",
    updatedDate: "-",
    id: 8,
  },
  {
    no: 9,
    branchId: "SBY",
    shipmentType: "Ritase",
    driverId: 2311111,
    driverName: "xxx",
    lastShipment: "Surabaya-Balikpapan",
    numberOfTrip: 5,
    hoursDriven: 40,
    healthResult: "Fit",
    operationResult: "pending",
    fatigueLevel: "medium",
    recommendation: "Boleh Lanjut",
    updatedFrom: "Nakes",
    updatedBy: "-",
    updatedDate: "-",
    id: 9,
  },
  {
    no: 10,
    branchId: "SBY",
    shipmentType: "Ritase",
    driverId: 2311111,
    driverName: "xxx",
    lastShipment: "Surabaya-Balikpapan",
    numberOfTrip: 5,
    hoursDriven: 40,
    healthResult: "Fit",
    operationResult: "pending",
    fatigueLevel: "low",
    recommendation: "Boleh Lanjut",
    updatedFrom: "Driver",
    updatedBy: "-",
    updatedDate: "-",
    id: 10,
  },
];

export const dummyDriverList = [
  {
    label: "Driver Name",
    value: "driver_name",
    options: [],
  },
  {
    label: "Fatigue Level",
    value: "fatigue_level",
    options: [
      {
        label: "Low",
        value: "low",
      },
      {
        label: "Medium",
        value: "medium",
      },
      {
        label: "High",
        value: "high",
      },
    ],
  },
  {
    label: "Health Result",
    value: "health_result",
    options: [
      {
        label: "Fit",
        value: "fit",
      },
      {
        label: "Fit With Note",
        value: "fit_with_note",
      },
      {
        label: "Unfit",
        value: "unfit",
      },
    ],
  },
  {
    label: "Recommendation",
    value: "recommendation",
    options: [
      {
        label: "Boleh Lanjut",
        value: "continue",
      },
      {
        label: "1 hari OFF",
        value: "break",
      },
    ],
  },
];

export const dummyBranchList = [
  {
    label: "Banjarmasin",
    value: "a",
  },
  {
    label: "Balikpapan",
    value: "b",
  },
  {
    label: "Jakarta",
    value: "c",
  },
  {
    label: "Makassar",
    value: "d",
  },
  {
    label: "Semarang",
    value: "e",
  },
  {
    label: "Surabaya",
    value: "f",
  },
];

export const dummyEmployeeList = [
  {
    label: "PKWT",
    value: "a",
  },
  {
    label: "MITRA",
    value: "b",
  },
];

export const dummyShipmentList = [
  {
    label: "Ritase",
    value: "a",
  },
  {
    label: "Dedicated",
    value: "b",
  },
];

export const dummyQuestionaire = {
  driverDeclaration: [
    {
      no: 1,
      question: "Apakah driver sudah cukup tidur minimal 6 jam?",
      answer: "yes",
    },
    {
      no: 2,
      question: "Apakah driver mengkonsumsi alkohol dan narkoba?",
      answer: "no",
    },
    {
      no: 3,
      question: "Apakah kondisi mata driver merah?",
      answer: "no",
    },
  ],
  healthCheck: [
    {
      no: 1,
      question: "Apakah driver sudah cukup tidur minimal 6 jam?",
      answer: "yes",
    },
    {
      no: 2,
      question: "Apakah driver mengkonsumsi alkohol dan narkoba?",
      answer: "no",
    },
    {
      no: 3,
      question: "Apakah kondisi mata driver merah?",
      answer: "no",
    },
  ],
};
