export const USER_VERIFICATION_BAD_REQ = "USER_VERIFICATION-006";
export const USER_VERIFICATION_INVALID = "USER_VERIFICATION-0010";
export const USER_VERIFICATION_INACTIVE = "USER_VERIFICATION-0011";
export const USER_VERIFICATION_EXPIRED = "USER_VERIFICATION-0012";
export const USER_VERIFICATION_VALID = "USER_VERIFICATION-0013";
